name: Deploy

on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Create
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            JWT_SECRET
            FEED_OWNER
            FEED_HOST
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          FEED_OWNER: ${{ secrets.HANDLE_NAME }}
          FEED_HOST: ${{ secrets.FEED_HOST }}
