name: Deploy

on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Check code
        run: pnpm run check
      - name: Deploy Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            JWT_SECRET
            FEED_OWNER
            FEED_HOST
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          FEED_OWNER: ${{ secrets.FEED_OWNER }}
          FEED_HOST: ${{ secrets.FEED_HOST }}
      - name: Publish Pages
        env:
          PAGES_PROJECT: ${{ secrets.PAGES_PROJECT }}
        if: ${{ env.PAGES_PROJECT != '' }}
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.PAGES_PROJECT }}
          directory: public
