name: Deploy Workers

on:
  repository_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'wrangler.toml'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Check code
        run: pnpm run check
      - name: Deploy Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            JWT_SECRET
            FEED_OWNER
            FEED_HOST
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          FEED_OWNER: ${{ secrets.FEED_OWNER }}
          FEED_HOST: ${{ secrets.FEED_HOST }}
