name: Publish Feed

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish Feed
    steps:
      - uses: actions/checkout@v4
      - run: node scripts/publish-feed.js
        env:
          FEED_HOST: ${{ secrets.FEED_HOST }}
          FEED_OWNER: ${{ secrets.FEED_OWNER }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
